AllCops:
  NewCops: enable
  Exclude:
    # generated Protobuf files
    - lib/smartdoor-ruby/pa_protobuf/*.rb

Naming/FileName:
  Exclude:
    - lib/smartdoor-ruby.rb

Metrics/ClassLength:
  Exclude:
    - lib/smartdoor-ruby/adapter_core.rb
    - lib/smartdoor-ruby/smartdoor_handler.rb

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
