# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: announcements.proto

require 'google/protobuf'

require 'announcement_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("announcements.proto", :syntax => :proto3) do
    add_message "PluginAdapter.Api.Announcements" do
      repeated :announcements, :message, 1, "PluginAdapter.Api.Announcement"
    end
  end
end

module PluginAdapter
  module Api
    Announcements = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PluginAdapter.Api.Announcements").msgclass
  end
end
